whatsappBtn = document.querySelector(".whatsapp");


var frases = [
    'safada tesuda rabuda pedaço de mal caminho vou te contar um segredo a meia noite',
    'amor, eu te amo pra sempre, amo cada momento juntinho cntg amo cada detalhezinho teu, amo teu cheiro, teu abraço tudo que envolva brenda leite eu sou absurdamente apaixonado, eu te amo muito',
    'tu é a melhor coisa que já aconteceu na minha vida, obrigado por ser tão maravilhosa pra mim',
    'tu é a pessoa mais especial e importante que já entrou na minha vida brendinha <3',
    'eu faria literalmente qualquer coisa pra ver o teu sorrisinho fofo o mais lindo que existe',
    'te amo minha dama minha donzela me manipula ss',
    'eu abri a galeria e tinha uma foto tua escrito eu te amo muito fofo dai passou todo o momento de ontem pela minha cabeça + o quanto eu te amo muito muito mutio nito muro',
    'amor eu simplesmente amo te ter na minha vida tu deu sentido a ela todo dia eu acordo e penso em como eu sou sortudo em ter uma mulher que posso chamar de minha e ainda por cima ela ser tão perfeita e me amar tanto quanto eu a amo. tu é minha princesa pra sempre a pessoa que eu faria qualquer coisa pra ver feliz e realizada obg por ser tão maravilhosa pra mim amor eu te amo com todo meu coração cada átomo meu ama brenda leite a minha preguiçosinha chatinha fã de filme romântico ruim, boa noite amor te amo',
    'amor eu te amo muito eu sou mt sortudo sabia', 
    'tu é MUITO linda amor puta merda',
    'quero te encher de beijinhos, AMANHÃ!!!',
    'te amo muito amor me fez mt bem os minutinhos a mais',
    'larguei varias bufas e tua mae entra no quarto bem na hora pra ajudar ela a colar o curativo',
    'amor te amo tu é a razão da minha vida eu amo te amo amo ser teu namoradinho faria de tudo por vc',
    'SIM, teu abraço é o melhor lugar do mundo amor puta que pariu mt bom',
    'finge que eu to ai e acabei de soltar uma bufa de baixo das coberta',
    'sexta feira estaremos juntinhos',
    'ui mano ta linda demais uma deusa uma rainha princesa cheirosa',
    'tu é perfeita amor te amo te amo te amo pra sempre',
    'mt fofinho mesmo adoro te encher de beijinhos',
    'eu amei tudo meu denguinho tu tava linda demais totalmente apaixonado',
    'funga meu bigode legal amor',
    'mt bom poder contar com alguém pra tudo e compartilhar lembranças momentos fofinhos tu sabe que a gente vai ficar junto pra sempre n tem volta',
    'te amo muuuito amor nosso find vai ser perfeito sem negatividade apenas patinhos e beijinhos e american horror story',
    'amanhã de noite vamos estar longe de tudo apenas beijinhos e amores te amo',
    'te amo amor aviso quando chegar tu é tudo pra mim ok','eu te amo minha gostosa minha princesa minha cheirosa',
    'eu te amo do fundo meu coração meu único e completo amor tu preenche meu coração durante toda a minha vida tu foi a unica capaz te amo te amo te amo n fica triste',
    'qualquer coisa to aqui meu docinho tu eh a pessoa mais especial e única na minha vida n esquece disso',
    'oq tu tava linda nesse dia eh absurdo',
    'malha legal vo enche essa bunda de beijo',
    'TE AMO MUITO PUTA MERDA COMO EU TE AMO',
    'EU TE AMO AMOR PRA SEMPRE',
    'te amo muito nene',
    'gosto quando to triste e tu fala com voz de nenê cmg mas isso ngm deve saber 👍🏻',
    'amor eu te amo infinitamente n tem palavras pra descrever o quanto tu é importante pra mim eu amo muito todas as tuas versões sem exceções eu amo te ter como namorada eu amo acordar sabendo que namoro a mulher mais perfeita que ja existiu e q vai existir',
    'eu te amo muito muito muito tu é tudo pra mim ❤️',
    'te amo te te amo te amo te amo tu eh a mulher mais gostosa e perfeita que existe na face da terra eu me derreto so de olhar qualquer partizinha do teu corpo qualquer detalhezinho eu sou absurdamente abaixonado pela brendinha eu n tenho duvidas de que tu eh a mulher da minha vida a minha rainha a namorada que eu sempre sonhei',
    'minha linda somos lindos casal mais bonito do mundo se duvida',
    'ALISA MEU PELO LEGAL TE AMO TE AMO TE AMO',
    'te amo muito amor meu pra sempre minha princesa',
    'te amo te amo a mulher mais linda de todo universo',
    'gostosa delicia esse biquinho na minha frente eu faço história',
    'quero peito 🤒🤧😖😖',
    'ui safada cheirosa gostosa delicia',
    'te amo minha missão na terra eh te fazer a mulher mais feliz do mundo eu te amo te amo te amo pra sempre gostosa fdp porra linda do caralho desgraca de mulher perfeita',
    'vamo ir pras cachoeiras e ficar la vivendo igual indigena',
    'TE AMO CONTA CMG EU AMO TE AMO TE AMO TE AMO SEMPRE AQ PRA VC ❤️❤️❤️❤️',
    'te amo eu te amo amo amo amo pra sempre eu e vc ok',
    'eu amo literalmente tudo em ti tu é a mulher mais perfeita TIPO A MAIS PERFEITA MESMO SEM EXAGERO QUE EXISTE EU SOU O HOMEM MAIS SORTUDO NESSA PORRA!!!!',
    'gostosa rainha deusa do meu coração meu docinho minha tudo eu te amo pra sempre tu eh literalmente perfeita em todos os sentidos-!!/!?!!',
    'to com muita saudade amor nunca mais fala que eu fico de boa longe de ti pf puta merda deu mais saudade ainda quero meu teu abracinho quentinho',
    'te amo meu amor tudo pela brendinha tudo fica fácil cntg na minha vida nenê',
    'eu tenho tanta sorte de te ter brendinha perfeita te amo',
    'eu te amo pra sempre juro pra sempre vou te amar sou totalmente brendizado',
    'n me vejo MESMO num mundo onde a gente n eh grudado um no outro',
    ' pra sempre a gente brendinha tu é minha vida meu tudo bizarro te amo absurdo so de tu me cafungar legal fez meu dia🥺',
    'tu é literalmente TUDINHO pra mim brendinha eu te amo pra sempre sempre sempre',
    'sempre que precisar meu amor só falar que eu vou vamos fazer assim agora pq porra ngm merece passar o domingo de noite numa deprê te amo muito amor, muito msm ❤️ conta comigo pra literalmente tudo eu faria qualquer coisa pra te ver felizinha',
    'minha mulher é a mais bela do universo eu não tenho dúvidas disso meu deus eu to transbordando de amor pela brendinha',
    'amo te encher de beijinhos eu faria e vou fazer isso pra sempre pode deixar eu amo amo amo te dar amores amo ver tu toda felizinha tu é perfeita',
    'gostosa gostosa gostosa aiaiai eu sou muito sortudo literalmente o homem mais sortudo do universo',
    'amo e acho perfeito teu corpinho perfeito as tetinha inchada a bunda gigantesca que eu amo encher de beijinhos a barriguinha inchada da tpm aiaiai linda demais',
    'manda em mim legal gatinha me manipula pf',
    'tu é a mulher mais linda e perfeita do universo obg obg obg destino por tu ser minha namorada',
    'eh mt bom amar e ser correspondido te amo muito meu amor 😝😝😍',
    'Harry Styles é muito bom mesmo amor agr vai tirando a roupa aí kkkkkk',
    'vc eh a pessoa mais gostosa e linda e cheirosa e princesa e meu raio de sol vc eh meu tudo te amo amô',
    'minha deusa minha dama minha rapunzel tu tem todo meu amor brendinha',
    'te amo absurdos minha dama',
    'eu literalmente te amo tlg LITERALMENTE',
    'bizarro o quanto eu te amo e o quanto eu te acho maravilhosa sério, tu é perfeita linda linda LINDA eu vou explodir',
    'tu é tão especial e única pra mim meu amor eu vou te amar por toda a eternidade eu não tenho dúvidas disso pode contar cmg pra qualquer coisa eu amo e sempre vou amar estar junto cntg!!',
    'eu te amo mais que tudo nesse mundo 😭',
    'amo quando a gente fala sobre nosso futuro não tenho dúvidas de que vamos ser felizes para sempre brendinha',
    'eu + tu + puss in boots 2, ss ou nn'
  ];

  function novafrase() {
    var aleatorio = Math.floor(Math.random() * (frases.length));
    document.getElementById('frase').innerHTML = frases[aleatorio];
  }

  whatsappBtn.addEventListener("click", () => {
    let whatsappUrl = 'https://wa.me/985458578';
    window.open(whatsappUrl)
  })